services:
    server:
        build: ./server
        ports:
            - "8000:8000"

        develop:
            watch:
                - action: sync
                  path: ./server
                  target: /app
                  ignore:
                      - .venv/

                - action: rebuild
                  path: ./server/pyproject.toml
