(
    BIKE_CATEGORY,
    BIKE_MAXPRICE,
    BIKE_MINPRICE,
    BIKE_SIZE,
    BIKE_REGION,
    REMOVE_ALERT,
    SELECT_REMOVE_ALERT,
    CONFIRM_REMOVE_ALERT,
) = range(8)

REGION_OPTIONS = ["Uusimaa", "Any"]
