x-common-env: &common-env
    SQLALCHEMY_DATABASE_URL: "sqlite:////app/data/database.db"

x-shared-volumes: &shared-volumes
    volumes:
        - ../data:/app/data # - /var/lib/bikewatch:/app/data # for production

services:
    scraper:
        build:
            context: ..
            dockerfile: docker/Dockerfile.scraper
        environment:
            <<: *common-env
            SCRAPING_FREQUENCY_MINUTES: 1
            SCRAPING_PAGE_LIMIT: 1
            GETREQ_RATE_LIMIT_SECONDS: 2
        <<: *shared-volumes

        entrypoint: ["/app/docker/entrypoint-scraper.sh"]

    bot:
        build:
            context: ..
            dockerfile: docker/Dockerfile.bot
        environment:
            <<: *common-env
        env_file:
            - ../.env
        <<: *shared-volumes

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
