services:
    scraper:
        build:
            context: ..
            dockerfile: docker/Dockerfile.scraper
        environment:
            SCRAPING_FREQUENCY_MINUTES: 60
        volumes:
            - ../data:/app/data

    backend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.backend
        ports:
            - "8000:8000"
        volumes:
            - ../data:/app/data
