x-common-env: &common-env
    SQLALCHEMY_DATABASE_URL: "sqlite:////app/data/database.db"

x-database-volume: &database-volume
    volumes:
        - ../data:/app/data # - /var/lib/bikewatch:/app/data # for production

services:
    scraper:
        build:
            context: ..
            dockerfile: docker/Dockerfile.scraper
        environment:
            <<: *common-env
            SCRAPING_FREQUENCY_MINUTES: 1
            SCRAPING_PAGE_LIMIT: 1
            GETREQ_RATE_LIMIT_SECONDS: 2

        <<: *database-volume
        entrypoint: ["/app/docker/entrypoint-scraper.sh"]

    # backend:
    #     build:
    #         context: ..
    #         dockerfile: docker/Dockerfile.backend
    #     ports:
    #         - "8000:8000"
    #     volumes:
    #         - ../data:/app/data

    bot:
        build:
            context: ..
            dockerfile: docker/Dockerfile.bot
        environment:
            <<: *common-env
        env_file:
            - ../.env
        <<: *database-volume
