FROM python:3.12-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY ./scraper/ /app

# Copy the uv lockfile into the container.
COPY pyproject.toml /app/pyproject.toml
COPY ./uv.lock /app/uv.lock

# Install the application dependencies.
WORKDIR /app
RUN uv sync --frozen --no-cache

# Run the scraper application by default
# CMD ["python3", "src/main.py"]
CMD ["uv", "run", "src/main.py"]