services:
    scraper:
        build:
            context: ..
            dockerfile: docker/Dockerfile.scraper
        environment:
            SCRAPING_FREQUENCY_MINUTES: 1
            SCRAPING_PAGE_LIMIT: 1
            GETREQ_RATE_LIMIT_SECONDS: 2
        volumes:
            - ../data:/app/data

    backend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.backend
        ports:
            - "8000:8000"
        volumes:
            - ../data:/app/data

    bot:
        build:
            context: ..
            dockerfile: docker/Dockerfile.bot
        env_file:
            - ../.env
        volumes:
            - ../data:/app/data
